# Goal - I have to Lint, Build, test the code for frontend and backend, 
# then push the images to docker hub

name: CI

on:
    push:
        branches: [advanced]

jobs:
    frontend-ci:
          runs-on: ubuntu-latest
          steps:
              # Check out the code
              - name: Check out the code
                uses: actions/checkout@v4

              # Code lint
              - name: Linting the code
                uses: actions/setup-node@v4
                with:
                  node-version: '20'
                  cache: 'npm' # Options: 'npm', 'yarn', or 'pnpm'
                  cache-dependency-path: frontend/package-lock.json

              - name: Install npm package
                run:  npm install

              - name: Run Linter
                run: npm run lint

              - name: Run Tests
                run: npm run test     
              #- Build
              #- Test
              #- Push 


    #backend-ci:



